[package]
name = "mitki-db"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
mitki-analysis.workspace = true
mitki-errors.workspace = true
salsa.workspace = true

[dev-dependencies]
mitki-inputs.workspace = true
